### ISSUE TITLE
PRNG Seed Codes for 6DCC1D29 Don't Match Sleipnir's Output

### ISSUE THREAD

**Issue by jjaldridge2009** [E-Sh4rk/EmeraldACE_web#1]
I was trying to set my PRNG state to a specific seed using the web tool, and wasn't able to confirm the location when doing actual RNG.

So to test the validity of the code generator, I found one of the seeds Sleipnir had already generated codes for:

6DCC1D29
![image](https://user-images.githubusercontent.com/16225603/113493884-7f40af80-94b1-11eb-8724-ccdd8315762f.png)

His Box code output for that seed was as follows:

```
  Box 1:  (FM...o♀S?n) [one ...]
  Box 2:  ( ?"FS?n )   [starts with space; righty "; ends with space]
  Box 3:  (?"XD...o  ) [righty "; one ...; ends with two spaces]
  Box 4:  (E5"!n   )   [righty "; ends with three spaces]
  Box 5:  (G/!nh♀!n)
  Box 6:  ( ?" ...Qn ) [starts with space; righty "; one space after "; one ...; ends with space]
  Box 7:  (?" ...?q  ) [righty "; one space after "; one ...; ends with two spaces]
  Box 8:  (EmFlo   )   [lower case L; ends with three spaces]
  Box 9:  (yLRom"Ro)   [righty "]
  Box 10: ( ?"FGEn )   [starts with space; righty "; ends with space]
  Box 11: (?" ...?q  ) [righty "; one space after "; one ...; ends with two spaces]
  Box 12: (E"STn   )   [lefty "; ends with three spaces]
  Box 13: (YN?nFNRo)
  Box 14: (S?n... Rn ) [one ...; one space after ...; ends with space]
  ```
  
  Your PRNG Seed code generator outputs the following.
  
  INPUT:
  
  ```
  @@ title = "Change PRNG Seed (ENG)"
@@ exit = "CertificateENG"

seed = 0x6DCC1D29

@@

movs r12, 0x3000000            %%  R12=3000000
adc r12,r12, 0x2D80            %%  R12=R12+2D80=3002D80
adc r12,r12, 0x3000            %%  R12=R12+3000=3005D80=PRNG state location
movs r11, { seed }  ?
str r11, [r12]!                %%  Store new seed in PRNG state location
```

OUTPUT:
```
F M … o 	E3B0C7C0	MOVS r12, #0x3000000
♀ S ? n 	E2ACCDB6	ADC r12, r12, #0x2d80
F S ? n 	E2ACCDC0	ADC r12, r12, #0x3000
r ” … o 	E3B0B2E6	MOVS r11, #0x6000000e
h ♀ ! n 	E2ABB6DC	ADC r11, r11, #0xdc00000
G / ! n 	E2ABBAC1	ADC r11, r11, #0xc1000
W D ! n 	E2ABBED1	ADC r11, r11, #0xd10
… ” ! n 	E2ABB2B0	ADC r11, r11, #0xb
␣ … ? q 	E5ACB000	STR r11, [r12, #0x0]!

Box  1: F M … o ♀ S ? n	[FM…o♀S?n]
Box  2: ␣ ␣ ␣ F S ? n ␣	[   FS?n ]
Box  3: ␣ ␣ r ” … o ␣ ␣	[  r”…o  ]
Box  4: ␣ h ♀ ! n ␣ ␣ ␣	[ h♀!n   ]
Box  5: G / ! n W D ! n	[G/!nWD!n]
Box  6: ␣ ␣ ␣ … ” ! n ␣	[   …”!n ]
Box  7: ␣ ␣ ␣ … ? q ␣ ␣	[   …?q  ]
Box  8: ␣ m F l o ␣ ␣ ␣	[ mFlo   ]
Box  9: y L R o m ” R o	[yLRom”Ro]
Box 10: ␣ ␣ ␣ F G E n ␣	[   FGEn ]
Box 11: ␣ ␣ ␣ … ? q ␣ ␣	[   …?q  ]
Box 12: ␣ “ S T n ␣ ␣ ␣	[ “STn   ]
Box 13: Y N ? n F N R o	[YN?nFNRo]
Box 14: S ? n … ␣ R n ␣	[S?n… Rn ]

Raw data (in hexadecimal):
C0 C7 B0 E3 B6 CD AC E2 FF 00 00 00 C0 CD AC E2 00 FF 00 00 E6 B2 B0 E3 00 00 FF 00 DC B6 AB E2 00 00 00 FF C1 BA AB E2 D1 BE AB E2 FF 00 00 00 B0 B2 AB E2 00 FF 00 00 00 B0 AC E5 00 00 FF 00 E1 C0 E0 E3 00 00 00 FF ED C6 CC E3 E1 B2 CC E3 FF 00 00 00 C0 C1 BF E2 00 FF 00 00 00 B0 AC E5 00 00 FF 00 B1 CD CE E2 00 00 00 FF D3 C8 AC E2 C0 C8 CC E3 FF CD AC E2 B0 00 CC E2 00 FF 

```

**Comment by jjaldridge2009** [comment]
For reference, I used the generator to create a code for a 16-bit seed of 0xf0de 

I was able to use this code effectively, so I know the form is working for 16-bit seeds just fine. Its possible my initial attempt at using a 32-bit seed was a typo, but the code did execute normally and show the certificate screen. I just couldn't confirm that the code took me to the seed I expected, as the Pokemon weren't matching.

**Comment by E-Sh4rk** [comment]
Thank you for your detailled report!
Indeed, the code generator does not produce the same output as Sleipnir's code.
However, I checked it on the seed 0x6DCC1D29 and it seems that both Sleipnir's and the generated codes are correct.

Actually, the difference is in how the seed value is computed.
Sleipnir does: D20+6000000A+C1000+DC00000-1=6DCC1D29
While the generator does: 6000000E+DC00000+C1000+D10+B=6DCC1D29
Both calculations are correct! :)
Another difference between the two codes is that the filler codes (the "no-operation" commands
used to fill the spaces where a 0xFF terminator lies) are not the same, but both are correct in this context.

Do not hesitate to open a new issue if you still have a problem :)
