### ISSUE TITLE
Potential bug with immediate value decomposer

### ISSUE THREAD

**Issue by c-poole** [E-Sh4rk/EmeraldACE_web#7]
movs r11, {0x7f8695d6 }  ?     will result in Arm.InvalidCommand in the output. If the register is changed to r12, things work fine and results in the following set of commands:

k I … o 	E3B0C3DF	MOVS r12, #0x7c000003
m M ? n 	E2ACC7E1	ADC r12, r12, #0x3840000
4 Q ? n 	E2ACCBA5	ADC r12, r12, #0x29400
z F ? n 	E2ACC0EE	ADC r12, r12, #0xee
q F ? n 	E2ACC0E5	ADC r12, r12, #0xe5

If I ask the code generator what box names correspond to these commands but with r11 swapped in place of r12, it turns out there is an invalid character. 

I would normally expect that the parser either finds a longer but writeable solution that works for the requested register

**Comment by E-Sh4rk** [comment]
Currently, the generator gives up if no solution is found for up to 5 opcodes. It is what is happening in your case.
Though, I am sure I can improve it so that it finds something, or at least print a more pertinent error message.
I will take a look.
